#+TITLE:     Emonad
#+AUTHOR:    Andrew Braunstein <bandrew> and Rafe Kettler <rkettler>
#+EMAIL:     bandrew@seas.upenn.edu -- rkettler@seas.upenn.edu
#+DATE:      2012-11-04 Sun
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport

* Description
  Emonad is a text editor that is similar to emacs, but written in
  Haskell. The frontend will be text only. The editor logic will be
  completely pure reducing bugs and complications. This will be an
  interesting design approach to text editors since most text editors,
  including emacs, are written with lots of mutable state. While emacs has
  elisp at its core, emonad will have Haskell at its core. Config
  files will be written in Haskell.

* Architecture
** Rope
   This is the data structure that holds the text of the buffer. We
   extended the rope library with a few extra functions that make it
   easier to use.
   - log time insertion and deletion
   - constant time length
** Buffer
   This is the data structure that deals with the buffer
   - Move the mark and point
   - Manipulate text
   - Save to a file
   - Load from a file
   - Paging
** BufferList
   This is the module that deals with the collection of buffers.
   - Add new buffers
   - Kill buffer
   - Switch between buffers
   - Transform the current buffer
** Editor
   This is the current state of the editor. It knows about the buffer
   list, the context of key presses, the minibuffer, and the terminal
   - Deals with user input
   - Switches between buffer and minibuffer
   - Reads user input (IO)
   - Sets the text in the minibuffer
** UI
   This is the code that draws the editor in the terminal
   - Primarily uses the vty library
   - Uses combinators to layout the page

* Additional Libraries
** Rope
   This is the efficient data structure that we use to store text
** Vty
   Terminal interaction library
** mtl
   Monads!!!
** directory
   Library that deals with the filesystem
** HUnit
   Unit testing
** QuickCheck
   Property based testing

* Installation instructions
  #+BEGIN_SRC
  cabal configure
  cabal install
  #+END_SRC
